from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field


class SubtitleSegment(BaseModel):
    start_ms: int
    end_ms: int
    text: str


BeatType = Literal[
    "setup",
    "inciting_incident",
    "rising_action",
    "climax",
    "resolution",
    "other",
]


class PageSpec(BaseModel):
    page_index: int
    paragraphs: list[str] = Field(default_factory=list, description="Semantic text blocks (Action, Dialogue, Reaction)")
    moment_id: str = Field(default="", description="Which analysis moment this page depicts")
    beat_type: BeatType = "other"
    # PRD-aligned: seconds
    image_timestamp_candidates_s: list[float] = Field(default_factory=list)
    alt_text: str = ""
    layout_hint: Literal["image_top", "image_bottom", "auto"] = "auto"

    @property
    def text(self) -> str:
        """Helper to get full text for validation/debugging."""
        return "\n\n".join(self.paragraphs)


class BookSpec(BaseModel):
    schema_version: str = "1.0"
    title: str
    pages: list[PageSpec]


# Analysis schemas (for LLM integration - Milestone B)

class Character(BaseModel):
    name: str
    role: str
    traits: list[str] = Field(default_factory=list)
    appearance: Optional[str] = None  # "adult woman with short brown hair..."
    pronoun: Optional[str] = None     # "she", "he", "they"


class Beat(BaseModel):
    beat_type: BeatType
    summary: str
    timestamp_range: tuple[float, float]  # (start_s, end_s)


class Moment(BaseModel):
    moment_id: str
    beat_type: BeatType
    timestamp_range: tuple[float, float]  # (start_s, end_s)
    visual_description: str
    key_dialogue: list[str] = Field(default_factory=list)
    screenshot_candidates_s: list[float] = Field(default_factory=list)
    emotional_beat: Optional[str] = None  # "excitement", "fear", "triumph"


class AnalysisResult(BaseModel):
    """Video analysis output schema (from MLX-VLM Qwen3-VL)."""
    title_candidates: list[str] = Field(default_factory=list)
    characters: list[Character] = Field(default_factory=list)
    beats: list[Beat] = Field(default_factory=list)
    moments: list[Moment] = Field(default_factory=list)


# Screenshot selection schemas (Milestone C - intelligent screenshot selection)

class VisualTarget(BaseModel):
    """
    Per-page "visual claim" + anchors used to find the best-matching frame.
    Generated by a text LLM from page text + analysis.
    """

    page_index: int
    visual_target: str  # Simple description of what the screenshot should show
    key_dialogue: list[str] = Field(default_factory=list)  # dialogue lines to search in subtitles
    key_actions: list[str] = Field(default_factory=list)  # action keywords to search in moments/subtitles


class SelectedFrame(BaseModel):
    """Final screenshot decision for a page."""

    page_index: int
    timestamp_s: float
    frame_path: str  # extracted PNG path
    visual_target: str
    # Debug metadata (helps diagnose anchor misses / bad scoring)
    window_start_s: float
    window_end_s: float
    anchor_reason: str = ""
    vlm_score: float = 0.0
    vlm_raw: str = ""
    fallback_used: Optional[str] = None
    low_quality: bool = False


class VisualTargetsResult(BaseModel):
    """Convenience wrapper for JSON-mode generation."""

    targets: list[VisualTarget] = Field(default_factory=list)


# PDF Rendering configuration

class PDFLayoutConfig(BaseModel):
    """PDF layout configuration schema."""
    page_size: tuple[float, float] = (595.276, 841.89)  # A4 in points
    margins: tuple[float, float, float, float] = (72, 72, 72, 72)  # L, R, T, B in points
    font_family: str = "Helvetica"
    title_font_size: int = 24
    body_font_size: int = 14
    body_leading: int = 18
    page_number_font_size: int = 10
    image_max_width: float = 360.0  # points
    image_max_height: float = 288.0  # points
    include_page_numbers: bool = True
    title_page_layout: Literal["center", "top"] = "center"


